// Generated by cpp11: do not edit by hand
// clang-format off

#include "openfhe_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
std::string openfhe_version_();
extern "C" SEXP _openfhe_openfhe_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(openfhe_version_());
  END_CPP11
}
// code.cpp
double openfhe_selftest_();
extern "C" SEXP _openfhe_openfhe_selftest_() {
  BEGIN_CPP11
    return cpp11::as_sexp(openfhe_selftest_());
  END_CPP11
}
// ctx.cpp
SEXP ctx_new_(std::string scheme, cpp11::list opts);
extern "C" SEXP _openfhe_ctx_new_(SEXP scheme, SEXP opts) {
  BEGIN_CPP11
    return cpp11::as_sexp(ctx_new_(cpp11::as_cpp<cpp11::decay_t<std::string>>(scheme), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(opts)));
  END_CPP11
}
// ctx.cpp
cpp11::list ctx_info_(CtxPtr xp);
extern "C" SEXP _openfhe_ctx_info_(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(ctx_info_(cpp11::as_cpp<cpp11::decay_t<CtxPtr>>(xp)));
  END_CPP11
}
// ctx.cpp
bool xp_is_null_(SEXP xp);
extern "C" SEXP _openfhe_xp_is_null_(SEXP xp) {
  BEGIN_CPP11
    return cpp11::as_sexp(xp_is_null_(cpp11::as_cpp<cpp11::decay_t<SEXP>>(xp)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_openfhe_ctx_info_",         (DL_FUNC) &_openfhe_ctx_info_,         1},
    {"_openfhe_ctx_new_",          (DL_FUNC) &_openfhe_ctx_new_,          2},
    {"_openfhe_openfhe_selftest_", (DL_FUNC) &_openfhe_openfhe_selftest_, 0},
    {"_openfhe_openfhe_version_",  (DL_FUNC) &_openfhe_openfhe_version_,  0},
    {"_openfhe_xp_is_null_",       (DL_FUNC) &_openfhe_xp_is_null_,       1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_openfhe(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
