// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
std::string openfhe_version_();
extern "C" SEXP _openfhe_openfhe_version_() {
  BEGIN_CPP11
    return cpp11::as_sexp(openfhe_version_());
  END_CPP11
}
// code.cpp
double openfhe_selftest_();
extern "C" SEXP _openfhe_openfhe_selftest_() {
  BEGIN_CPP11
    return cpp11::as_sexp(openfhe_selftest_());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_openfhe_openfhe_selftest_", (DL_FUNC) &_openfhe_openfhe_selftest_, 0},
    {"_openfhe_openfhe_version_",  (DL_FUNC) &_openfhe_openfhe_version_,  0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_openfhe(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
