#' Homomorphic encryption context
#'
#' An `FHEContext` holds an OpenFHE crypto context: the scheme (CKKS, BFV or
#' BGV), its parameters, and -- as they are generated -- the evaluation keys
#' attached to it.  Create one with [fhe_context()]; almost every other
#' function in the package operates relative to a context.
#'
#' Contexts (and all other openfhe objects) reference native memory through
#' an external pointer, so they cannot be persisted with [saveRDS()] /
#' [save()]; use `save_fhe()`/`load_fhe()` (available from a later phase)
#' instead.  An object restored by R's own serialisation is "stale": it
#' prints as such and any use raises an error of class
#' `openfhe_stale_pointer`.
#'
#' @slot ptr External pointer to the native OpenFHE crypto context.
#' @slot scheme The scheme: `"CKKS"`, `"BFV"` or `"BGV"`.
#' @slot params Named list of the normalised parameters the context was
#'   created with (see [fhe_context()]).
#' @slot features Character vector of enabled OpenFHE feature sets.
#' @slot cache Environment caching context facts (ring dimension, slot
#'   count, ...) and key-generation state, used for fast introspection and
#'   good error messages.
#'
#' @seealso [fhe_context()]
#' @export
setClass(
  "FHEContext",
  slots = c(
    ptr      = "externalptr",
    scheme   = "character",
    params   = "list",
    features = "character",
    cache    = "environment"
  )
)

# Raise a classed error if `x` holds a stale external pointer (e.g. the
# object was restored with readRDS()/load() in a fresh session).
check_live <- function(x) {
  ptr <- if (isVirtualClass(class(x))) NULL else methods::slot(x, "ptr")
  if (xp_is_null_(ptr)) {
    stop_stale_pointer(call = sys.call(-1))
  }
  invisible(x)
}

#' Encryption keys
#'
#' An `FHEKeys` object bundles the public and secret halves of a key pair
#' generated by [keygen()] for one [FHEContext-class].  The `public_key`
#' (an `FHEPublicKey`) suffices to [encrypt()]; the `secret_key` (an
#' `FHESecretKey`) is required to [decrypt()] and must be kept private.
#' Evaluation keys (relinearisation, sum and rotation keys) are held
#' inside the context itself, not in this object.
#'
#' Like all openfhe objects, keys reference native memory and cannot be
#' persisted with [saveRDS()]/[save()]; use `save_fhe()`/`load_fhe()`
#' (available from a later phase) instead.
#'
#' @slot ptr External pointer to the native OpenFHE key
#'   (`FHEPublicKey`/`FHESecretKey` only).
#' @slot public_key The `FHEPublicKey` half of the pair.
#' @slot secret_key The `FHESecretKey` half of the pair.
#' @slot context The [FHEContext-class] the keys belong to.
#'
#' @seealso [keygen()], [encrypt()], [decrypt()]
#' @name FHEKeys-class
#' @aliases FHEPublicKey-class FHESecretKey-class
#' @export
setClass(
  "FHEPublicKey",
  slots = c(ptr = "externalptr", context = "FHEContext")
)

#' @rdname FHEKeys-class
#' @export
setClass(
  "FHESecretKey",
  slots = c(ptr = "externalptr", context = "FHEContext")
)

#' @rdname FHEKeys-class
#' @export
setClass(
  "FHEKeys",
  slots = c(
    public_key = "FHEPublicKey",
    secret_key = "FHESecretKey",
    context    = "FHEContext"
  )
)

#' Encrypted vector
#'
#' A `Ciphertext` is one encrypted R vector: all of its elements are packed
#' into the SIMD slots of a single OpenFHE ciphertext.  Create one with
#' [encrypt()]; recover the plaintext with [decrypt()].  The true R length
#' is recorded so that decryption never exposes slot padding.
#'
#' @slot ptr External pointer to the native OpenFHE ciphertext.
#' @slot context The [FHEContext-class] the ciphertext was encrypted under.
#' @slot length The true length of the encrypted vector.
#'
#' @seealso [encrypt()], [decrypt()]
#' @export
setClass(
  "Ciphertext",
  slots = c(
    ptr     = "externalptr",
    context = "FHEContext",
    length  = "integer"
  )
)

#' @describeIn FHEContext-class Compact description of the context:
#'   scheme, ring dimension, slot count, depth, security and enabled
#'   features.
#' @param object An `FHEContext`.
#' @export
setMethod("show", "FHEContext", function(object) {
  cat(sprintf("<OpenFHE %s context>\n", object@scheme))
  if (xp_is_null_(object@ptr)) {
    cat("  (stale: restored from an earlier R session; recreate the context",
        "or use load_fhe())\n")
    return(invisible(object))
  }
  sec <- if (is.na(object@params$security)) {
    "none (toy parameters, NOT secure)"
  } else {
    sprintf("%d-bit", object@params$security)
  }
  cat(sprintf(
    "  ring dimension %d (%d slots) | mult depth %d | security: %s\n",
    ring_dim(object), slot_count(object), mult_depth(object), sec
  ))
  cat(sprintf("  features: %s\n", paste(object@features, collapse = ", ")))
  invisible(object)
})

# Shared stale-pointer banner for show methods; returns TRUE if stale.
show_stale <- function(ptr) {
  if (xp_is_null_(ptr)) {
    cat("  (stale: restored from an earlier R session; recreate the object",
        "or use load_fhe())\n")
    TRUE
  } else {
    FALSE
  }
}

# One-line summary of the evaluation keys attached to a context.
eval_key_summary <- function(ctx) {
  rot <- ctx@cache$rotations
  paste(c(
    if (isTRUE(ctx@cache$mult_key)) "relinearisation",
    if (isTRUE(ctx@cache$sum_keys)) "sum",
    if (length(rot)) {
      if (length(rot) > 8) {
        sprintf("rotations (%d indices)", length(rot))
      } else {
        sprintf("rotations (%s)", paste(rot, collapse = ", "))
      }
    }
  ), collapse = " | ")
}

#' @describeIn FHEKeys-class Compact description of the key set and the
#'   evaluation keys generated so far.
#' @param object An `FHEKeys`, `FHEPublicKey` or `FHESecretKey` object.
#' @export
setMethod("show", "FHEKeys", function(object) {
  cat(sprintf("<OpenFHE %s key set>\n", object@context@scheme))
  if (show_stale(object@secret_key@ptr)) {
    return(invisible(object))
  }
  cat("  public + secret key\n")
  cat(sprintf("  evaluation keys: %s\n", eval_key_summary(object@context)))
  invisible(object)
})

#' @describeIn FHEKeys-class Compact description of a public key.
#' @export
setMethod("show", "FHEPublicKey", function(object) {
  cat(sprintf("<OpenFHE %s public key>\n", object@context@scheme))
  show_stale(object@ptr)
  invisible(object)
})

#' @describeIn FHEKeys-class Compact description of a secret key.
#' @export
setMethod("show", "FHESecretKey", function(object) {
  cat(sprintf("<OpenFHE %s secret key> (keep private)\n",
              object@context@scheme))
  show_stale(object@ptr)
  invisible(object)
})

#' @describeIn Ciphertext-class Compact description of an encrypted vector:
#'   its length, scheme and multiplicative level.
#' @param object A `Ciphertext`.
#' @export
setMethod("show", "Ciphertext", function(object) {
  cat(sprintf("<Encrypted vector[%d]>", object@length))
  if (xp_is_null_(object@ptr)) {
    cat("\n")
    show_stale(object@ptr)
    return(invisible(object))
  }
  cat(sprintf(" %s | level %d of %d\n",
              object@context@scheme, ct_level_(object@ptr),
              mult_depth(object@context)))
  invisible(object)
})

#' @describeIn Ciphertext-class The true length of the encrypted vector.
#' @param x A `Ciphertext`.
#' @export
setMethod("length", "Ciphertext", function(x) x@length)
