# Generated by cpp11: do not edit by hand

openfhe_version_ <- function() {
  .Call(`_openfhe_openfhe_version_`)
}

openfhe_selftest_ <- function() {
  .Call(`_openfhe_openfhe_selftest_`)
}

ctx_new_ <- function(scheme, opts) {
  .Call(`_openfhe_ctx_new_`, scheme, opts)
}

ctx_info_ <- function(xp) {
  .Call(`_openfhe_ctx_info_`, xp)
}

xp_is_null_ <- function(xp) {
  .Call(`_openfhe_xp_is_null_`, xp)
}

enc_real_ <- function(ctx, pk, x) {
  .Call(`_openfhe_enc_real_`, ctx, pk, x)
}

enc_int_ <- function(ctx, pk, x) {
  .Call(`_openfhe_enc_int_`, ctx, pk, x)
}

dec_real_ <- function(ctx, sk, ct, n) {
  .Call(`_openfhe_dec_real_`, ctx, sk, ct, n)
}

dec_int_ <- function(ctx, sk, ct, n) {
  .Call(`_openfhe_dec_int_`, ctx, sk, ct, n)
}

ct_level_ <- function(ct) {
  .Call(`_openfhe_ct_level_`, ct)
}

ct_text_ <- function(ct) {
  .Call(`_openfhe_ct_text_`, ct)
}

pk_text_ <- function(pk) {
  .Call(`_openfhe_pk_text_`, pk)
}

sk_text_ <- function(sk) {
  .Call(`_openfhe_sk_text_`, sk)
}

keygen_ <- function(ctx, sum) {
  .Call(`_openfhe_keygen_`, ctx, sum)
}

rot_keygen_ <- function(ctx, sk, idx) {
  invisible(.Call(`_openfhe_rot_keygen_`, ctx, sk, idx))
}
